#!/bin/bash
URL="http://mywebloadbalancer-1736393159.us-east-1.elb.amazonaws.com:3000"
for i in {1..1000}; do
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
  curl $URL && sleep 0.1 & 
done
