Parameters:
  SSHKey:
    Description: Webserver-SSH-Key.
    Type: String
    Default: Webserver
  StackName:
    Description: Please enter name of Base StackName
    Type: String
    Default: MyBase

Resources:
  # Security Group
  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: MySG
      GroupName: MySG
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 
      Tags: 
        - Key: Name
          Value: MySG
      VpcId: !ImportValue
        'Fn::Sub': "${StackName}:VPC"

  MyFistInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SSHKey
      ImageId: ami-033b95fb8079dc481
      InstanceType: t2.micro
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue
            'Fn::Sub': "${StackName}:MyFirstSubnet"
          GroupSet: 
            - !Ref MySG
      Tags:
        - Key: Name
          Value: MyFistInstance
      UserData:        

  MySecondInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SSHKey
      ImageId: ami-033b95fb8079dc481
      InstanceType: t2.micro
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          SubnetId: !ImportValue
            'Fn::Sub': "${StackName}:MyFirstPrivateSubnet"
          GroupSet: 
            - !Ref MySG
      Tags:
        - Key: Name
          Value: MySecondInstance
      UserData:
          


